### ISSUE TITLE
sample-script/p_steps/step_03_T2_create_exclusion_criteria.R

### ISSUE THREAD

**Issue by vjolahoxhaj** [IMI-ConcePTION/sample-script#4]
output_spells_category_enriched <- output_spells_category_enriched[entry_spell_category>date_of_birth,one_year_obs:=entry_spell_category+1*365][entry_spell_category<=date_of_birth,one_year_obs:=date_of_birth]

If you are trying to first add 1 to entry_spell_category and then multiply by 365, I think you need to put the expression inside parentheses, because at this moment it is only multiplying by 365.

output_spells_category_enriched <- output_spells_category_enriched[entry_spell_category>date_of_birth,one_year_obs:=(entry_spell_category+1)*365][entry_spell_category<=date_of_birth,one_year_obs:=date_of_birth]

**Comment by RosaMGini** [comment]
Dear Vjola, thanks for your comment!

The expression is correct, lookback is 1 year in this protocol

I left 1 because in other protocols this can be longer lookback

**Comment by vjolahoxhaj** [comment]
Great.😊
