### ISSUE TITLE
sample-script/p_parameters/concept_sets.R 

### ISSUE THREAD

**Issue by vjolahoxhaj** [IMI-ConcePTION/sample-script#5]
In line 162(# COVDIAB) I get this error.
Error in concept_set_codes_our_study[["COVDIAB"]][["ICD9"]] <- c("250",  : 
  more elements supplied than there are to replace

#Code
# COVDIAB
          concept_set_codes_our_study[["COVDIAB"]][["ICD9"]] <- c("250.0")
          concept_set_codes_our_study[["COVDIAB"]][["ICD9"]] <-c("250","250.0","250.1","250.5","250.6","250.7","250.9")

I suspect this is because when it first tries to create the first double list, since there is only one element it fails and instead creates a vector. When you try to create the next double list within the COVDIAB list, it doesn't allow it because now the type of COVDIAB is character rather than list.

**Comment by OlgaPaoletti** [comment]
Which version of R are you using? We use version 4 and this issue is solved in this R version.

**Comment by vjolahoxhaj** [comment]
I was using 3.6. You were right. It works fine with version 4. Thanks for
your help.

**Comment by OlgaPaoletti** [comment]
To have R version 4 is essential. We will include this in the requirements.
Thank you for pointing it out.
